### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by felippepuhle** [entria/graphql-dataloader-boilerplate#15]
As a Windows user, I'm experiencing some troubles like:

- can't run 'build' script (windows does not have 'rm' command)

- can't run 'start' or 'watch' due some problem with bcrypt:
```
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/index.js`
C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\build\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\build\Debug\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\build\Release\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\out\Debug\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\Debug\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\out\Release\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\Release\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\build\default\bcrypt_lib.node
 → C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\compiled\7.5.0\win32\x64\bcrypt_lib.node
    at bindings (C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\bcrypt-as-promised\index.js:5:14)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Felippe R. Puhle\Documents\Projetos\teste\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by sibelius** [comment]
`rm` could be resolved using something like this: https://github.com/isaacs/rimraf

`npm rebuild` could solve your bcrypt problem

**Comment by felippepuhle** [comment]
`npm rebuild` didn't work because I don't have Windows SDK installed.

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\Felipp
e R. Puhle\Documents\Projetos\teste\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
```

I'm downloading it, later I'll give you a feedback. Thanks!

**Comment by lucasbento** [comment]
I think it's valid to remove `bcrypt` since it is a lot of trouble to compile.

We may also consider using a javascript-only solution as https://github.com/shaneGirish/bcrypt-nodejs.

**Comment by sibelius** [comment]
@felippepuhle let us know if works with windows sdk

I would like to keep using native bcrypt for performance reasons

**Comment by lucasbento** [comment]
@sibelius: what exactly are those performance reasons?

Having an user downloading a huge package just to run a boilerplate is not good at all.

**Comment by felippepuhle** [comment]
Just installing windows sdk didn't work here.

Found this: https://github.com/nodejs/node-gyp#installation
Using  `npm install --global --production windows-build-tools` didn't work too, so, I decided to install tools and configuration manually - option 2. Seems to be alright now!

**Comment by sibelius** [comment]
tks, can we close this?

**Comment by felippepuhle** [comment]
As you wish @sibelius, soon I'll send a PR to fix `rm -rf` on Windows... thanks!

**Comment by sibelius** [comment]
@felippepuhle please reopen if u have any more problem
